spring:
  application:
    name: currency-conversion-service 
    
server:
  port: 8102
    
eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
      instance: 
      hostname: localhost

    