spring:
  application:
    name: currency-exchange-service 
  datasource:    url: jdbc:h2:mem:testdb 
    
server:
  port: 8000
  
eureka:  client:    register-with-eureka: true 
    fetch-registry: true     serviceUrl:      defaultZone: http://localhost:8761/eureka 
      instance: 
      hostname: localhost 
      
